seed: 1024

train:
  epochs: 50
  batch: 50
  workers: 4
  gradient_accumulation: 1

validation:
  freq: 1
  batch: 256
  workers: 4

train_data:
  name: Cifar10
  fold: 0
  params:
    transformer: Default
    resize: 224x224

validation_data:
  name: Cifar10
  fold: 0
  params:
    transformer: Default
    resize: 224x224

model:
  name: Resnet50
  classes: 10
  prediction_type: Classification
  tune_type: FineTuning
  params:
    fc_drop_out_0: 0.2
    fc_drop_out_1: 0.2

optimizer:
  name: AdamW
  params:
    lr: 0.001

scheduler:
  name: CosineAnnealingLR
  params:
    T_max: 10

loss:
  name: CrossEntropyLoss
